import { Job } from '../types';

export const INITIAL_JOBS: Job[] = [
  {
    "id": "job-1",
    "companyId": "comp-1",
    "companyName": "Zoho Corporation",
    "companyLogo": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    "companyHub": "OMR (IT Corridor)",
    "title": "Associate Software Developer (Freshers 2025/2026)",
    "slug": "zoho-associate-software-developer-fresher",
    "descriptionSnippet": "We are hiring fresh engineering graduates to work on Zoho core product suites, database engines, and AI applications. Open to 0-1 years of experience with strong programming fundamentals in Java, C++, or Python.",
    "primaryCategory": "SaaS / Enterprise Software",
    "isEngineering": true,
    "engineeringSubcategory": "Software Engineering",
    "technologies": [
      "Java",
      "C++",
      "Python",
      "SQL",
      "Algorithms"
    ],
    "jobType": "Full-time",
    "workplaceType": "On-site",
    "experienceLevel": "Fresher / Entry (0-1 yrs)",
    "isFresher": true,
    "fresherConfidence": 98,
    "isInternship": false,
    "salaryRange": "₹6,50,000 - ₹9,50,000 / yr",
    "location": "Estancia IT Park / OMR, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://www.zoho.com/careers/job-details.html?id=fresher-dev-chennai",
    "sourceRecordId": "ZOHO-DEV-2026-01",
    "firstSeenAt": "2026-09-01T06:00:00Z",
    "lastSeenAt": "2026-09-01T14:00:00Z",
    "lastVerifiedAt": "2026-09-01T14:00:00Z",
    "freshnessStatus": "NEW",
    "verificationStatus": "VERIFIED",
    "duplicateGroupId": "dup-zoho-fresher-1",
    "alternateSources": [
      {
        "sourceName": "LinkedIn",
        "url": "https://linkedin.com/jobs/view/zoho-fresher-chennai",
        "discoveredAt": "2026-09-01T07:30:00Z"
      },
      {
        "sourceName": "Naukri",
        "url": "https://naukri.com/job-listings-zoho-software-dev-chennai",
        "discoveredAt": "2026-09-01T08:00:00Z"
      }
    ],
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-2",
    "companyId": "comp-1",
    "companyName": "Zoho Corporation",
    "companyLogo": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
    "companyHub": "OMR (IT Corridor)",
    "title": "Full Stack Engineer - Zoho CRM & AI Platform",
    "slug": "zoho-fullstack-engineer-crm",
    "descriptionSnippet": "Architect and build high-performance web components for Zoho CRM using React, TypeScript, and Java microservices. Help integrate generative AI assistants into workflow automations.",
    "primaryCategory": "SaaS / Enterprise Software",
    "isEngineering": true,
    "engineeringSubcategory": "Full Stack",
    "technologies": [
      "React",
      "TypeScript",
      "Java",
      "PostgreSQL",
      "Machine Learning"
    ],
    "jobType": "Full-time",
    "workplaceType": "On-site",
    "experienceLevel": "Mid (3-5 yrs)",
    "isFresher": false,
    "fresherConfidence": 0,
    "isInternship": false,
    "salaryRange": "₹14,00,000 - ₹22,00,000 / yr",
    "location": "Estancia IT Park, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://www.zoho.com/careers/job-details.html?id=fs-crm-chennai",
    "firstSeenAt": "2026-08-28T10:00:00Z",
    "lastSeenAt": "2026-09-01T12:00:00Z",
    "lastVerifiedAt": "2026-09-01T12:00:00Z",
    "freshnessStatus": "ACTIVE",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-3",
    "companyId": "comp-2",
    "companyName": "Freshworks",
    "companyLogo": "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Perungudi & Kandanchavadi",
    "title": "Frontend Engineer (React / TypeScript)",
    "slug": "freshworks-frontend-engineer-react",
    "descriptionSnippet": "Join Freshservice engineering team in Global Infocity, Perungudi. Build lightning-fast UI components with React 19, TypeScript, and Tailwind for our flagship enterprise ITSM product.",
    "primaryCategory": "SaaS / Enterprise Software",
    "isEngineering": true,
    "engineeringSubcategory": "Frontend",
    "technologies": [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "GraphQL"
    ],
    "jobType": "Full-time",
    "workplaceType": "Hybrid",
    "experienceLevel": "Junior (1-3 yrs)",
    "isFresher": false,
    "fresherConfidence": 15,
    "isInternship": false,
    "salaryRange": "₹12,00,000 - ₹18,00,000 / yr",
    "location": "Global Infocity Park, Perungudi, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Greenhouse / Lever ATS",
    "originalUrl": "https://boards.greenhouse.io/freshworks/jobs/4982173",
    "sourceRecordId": "FRSH-GH-4982173",
    "firstSeenAt": "2026-08-30T11:00:00Z",
    "lastSeenAt": "2026-09-01T15:00:00Z",
    "lastVerifiedAt": "2026-09-01T15:00:00Z",
    "freshnessStatus": "RECENTLY_VERIFIED",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-4",
    "companyId": "comp-7",
    "companyName": "Kovai.co",
    "companyLogo": "https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=128&auto=format&fit=crop&q=80",
    "companyHub": "DLF Porur & Manapakkam",
    "title": "Software Engineer - .NET & C# (Fresher & Junior Welcome)",
    "slug": "kovai-software-engineer-dotnet-fresher",
    "descriptionSnippet": "Kovai.co is hiring C# & .NET developers for Document360 and Turbo360 products in DLF Cybercity Chennai. Looking for candidates passionate about .NET 8, ASP.NET Core, and Microsoft Azure.",
    "primaryCategory": "SaaS / Enterprise Software",
    "isEngineering": true,
    "engineeringSubcategory": "Backend",
    "technologies": [
      ".NET",
      "C#",
      "Azure",
      "SQL",
      "PostgreSQL"
    ],
    "jobType": "Full-time",
    "workplaceType": "On-site",
    "experienceLevel": "Fresher / Entry (0-1 yrs)",
    "isFresher": true,
    "fresherConfidence": 92,
    "isInternship": false,
    "salaryRange": "₹6,00,000 - ₹9,00,000 / yr",
    "location": "DLF Cybercity, Porur / Manapakkam, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://www.kovai.co/careers/dotnet-developer-chennai/",
    "firstSeenAt": "2026-09-01T04:00:00Z",
    "lastSeenAt": "2026-09-01T13:00:00Z",
    "lastVerifiedAt": "2026-09-01T13:00:00Z",
    "freshnessStatus": "NEW",
    "verificationStatus": "VERIFIED",
    "duplicateGroupId": "dup-kovai-dotnet-1",
    "alternateSources": [
      {
        "sourceName": "LinkedIn",
        "url": "https://linkedin.com/jobs/view/kovai-dotnet-developer-chennai",
        "discoveredAt": "2026-09-01T05:00:00Z"
      }
    ],
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-5",
    "companyId": "comp-3",
    "companyName": "Chargebee",
    "companyLogo": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Sholinganallur",
    "title": "Software Development Engineer II (Java / Spring Boot / Distributed Systems)",
    "slug": "chargebee-sde-2-java-backend",
    "descriptionSnippet": "Scale our billing & revenue infrastructure processing billions of dollars in recurring transactions. Deep experience in high-throughput Java, distributed locks, Kafka, and PostgreSQL required.",
    "primaryCategory": "FinTech",
    "isEngineering": true,
    "engineeringSubcategory": "Backend",
    "technologies": [
      "Java",
      "Spring Boot",
      "Kafka",
      "PostgreSQL",
      "AWS",
      "Redis",
      "Docker"
    ],
    "jobType": "Full-time",
    "workplaceType": "Hybrid",
    "experienceLevel": "Mid (3-5 yrs)",
    "isFresher": false,
    "fresherConfidence": 0,
    "isInternship": false,
    "salaryRange": "₹22,00,000 - ₹34,00,000 / yr",
    "location": "OMR, Sholinganallur, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "LinkedIn",
    "originalUrl": "https://www.linkedin.com/jobs/view/chargebee-sde2-chennai",
    "firstSeenAt": "2026-08-25T08:00:00Z",
    "lastSeenAt": "2026-09-01T11:00:00Z",
    "lastVerifiedAt": "2026-09-01T11:00:00Z",
    "freshnessStatus": "ACTIVE",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-6",
    "companyId": "comp-5",
    "companyName": "Agnikul Cosmos",
    "companyLogo": "https://images.unsplash.com/photo-1517976487588-4a47d0d0f723?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Tidel Park & Tharamani",
    "title": "Avionics & Flight Software Engineer (C++ / Embedded Linux)",
    "slug": "agnikul-avionics-flight-software-engineer",
    "descriptionSnippet": "Write mission-critical flight software for Agnibaan orbital launch vehicles at IIT Madras Research Park. Experience in real-time operating systems (RTOS), C++, sensor telemetry, and hardware-in-the-loop simulation.",
    "primaryCategory": "SpaceTech & Defense",
    "isEngineering": true,
    "engineeringSubcategory": "Embedded & IoT",
    "technologies": [
      "C++",
      "Embedded & IoT",
      "Python",
      "Linux",
      "ROS"
    ],
    "jobType": "Full-time",
    "workplaceType": "On-site",
    "experienceLevel": "Junior (1-3 yrs)",
    "isFresher": false,
    "fresherConfidence": 20,
    "isInternship": false,
    "salaryRange": "₹10,00,000 - ₹16,00,000 / yr",
    "location": "IIT Madras Research Park, Tharamani, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://agnikul.in/#/careers/avionics-dev",
    "firstSeenAt": "2026-08-29T09:00:00Z",
    "lastSeenAt": "2026-09-01T14:30:00Z",
    "lastVerifiedAt": "2026-09-01T14:30:00Z",
    "freshnessStatus": "ACTIVE",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-7",
    "companyId": "comp-9",
    "companyName": "Mad Street Den (Vue.ai)",
    "companyLogo": "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Tidel Park & Tharamani",
    "title": "Computer Vision & GenAI Research Intern (6 Months)",
    "slug": "vue-ai-computer-vision-research-intern",
    "descriptionSnippet": "Work alongside world-class AI researchers at Ramanujan IT City / IITM corridor. Experiment with diffusion models, multimodal transformers, and visual search algorithms using PyTorch and Python.",
    "primaryCategory": "DeepTech & AI",
    "isEngineering": true,
    "engineeringSubcategory": "ML & AI Engineering",
    "technologies": [
      "Python",
      "Machine Learning",
      "PyTorch",
      "TensorFlow",
      "FastAPI"
    ],
    "jobType": "Internship",
    "workplaceType": "Hybrid",
    "experienceLevel": "Fresher / Entry (0-1 yrs)",
    "isFresher": true,
    "fresherConfidence": 95,
    "isInternship": true,
    "salaryRange": "₹35,000 - ₹50,000 / month stipend",
    "location": "Ramanujan IT City, Tharamani, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://vue.ai/careers/ai-intern-chennai",
    "firstSeenAt": "2026-09-01T08:00:00Z",
    "lastSeenAt": "2026-09-01T15:00:00Z",
    "lastVerifiedAt": "2026-09-01T15:00:00Z",
    "freshnessStatus": "NEW",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-8",
    "companyId": "comp-8",
    "companyName": "SuperOps.ai",
    "companyLogo": "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Perungudi & Kandanchavadi",
    "title": "Cloud DevOps & Site Reliability Engineer (AWS / Kubernetes)",
    "slug": "superops-cloud-devops-sre",
    "descriptionSnippet": "Maintain 99.99% reliability across our multi-tenant SaaS architecture. Manage AWS EKS clusters, Terraform pipelines, Prometheus monitoring, and automated disaster recovery.",
    "primaryCategory": "SaaS / Enterprise Software",
    "isEngineering": true,
    "engineeringSubcategory": "DevOps & Cloud",
    "technologies": [
      "AWS",
      "Docker",
      "Kubernetes",
      "Python",
      "PostgreSQL",
      "Redis"
    ],
    "jobType": "Full-time",
    "workplaceType": "Hybrid",
    "experienceLevel": "Mid (3-5 yrs)",
    "isFresher": false,
    "fresherConfidence": 0,
    "isInternship": false,
    "salaryRange": "₹18,00,000 - ₹28,00,000 / yr",
    "location": "Perungudi OMR, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Wellfound",
    "originalUrl": "https://wellfound.com/company/superops-ai/jobs/devops-sre-chennai",
    "firstSeenAt": "2026-08-27T12:00:00Z",
    "lastSeenAt": "2026-09-01T10:00:00Z",
    "lastVerifiedAt": "2026-09-01T10:00:00Z",
    "freshnessStatus": "ACTIVE",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-9",
    "companyId": "comp-11",
    "companyName": "TVS Digital & Mobility Tech",
    "companyLogo": "https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Guindy (SIDCO / Olympia)",
    "title": "Embedded Firmware Developer - EV Powertrain & BMS",
    "slug": "tvs-embedded-firmware-ev-powertrain",
    "descriptionSnippet": "Develop Battery Management Systems (BMS) and Motor Controller firmware for new electric scooter platforms. Strong C/C++, CAN bus, and microcontrollers experience in Olympia / Guindy tech center.",
    "primaryCategory": "AutoTech & EV",
    "isEngineering": true,
    "engineeringSubcategory": "Embedded & IoT",
    "technologies": [
      "C#",
      "Embedded & IoT",
      "Python",
      "Hardware"
    ],
    "jobType": "Full-time",
    "workplaceType": "On-site",
    "experienceLevel": "Junior (1-3 yrs)",
    "isFresher": false,
    "fresherConfidence": 10,
    "isInternship": false,
    "salaryRange": "₹9,00,000 - ₹15,00,000 / yr",
    "location": "Guindy Industrial Estate, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Naukri",
    "originalUrl": "https://www.naukri.com/job-listings-tvs-ev-embedded-chennai",
    "firstSeenAt": "2026-08-31T09:00:00Z",
    "lastSeenAt": "2026-09-01T13:00:00Z",
    "lastVerifiedAt": "2026-09-01T13:00:00Z",
    "freshnessStatus": "ACTIVE",
    "verificationStatus": "VERIFIED",
    "isFeatured": false,
    "isSeedData": true
  },
  {
    "id": "job-10",
    "companyId": "comp-10",
    "companyName": "Vivriti Capital / Yubi",
    "companyLogo": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Guindy (SIDCO / Olympia)",
    "title": "QA & Test Automation Engineer (Playwright / Java / API)",
    "slug": "yubi-qa-automation-engineer",
    "descriptionSnippet": "Lead quality engineering for our enterprise loan origination platform. Write automated regression suites with Playwright, TestNG, and Postman API contract testing.",
    "primaryCategory": "FinTech",
    "isEngineering": true,
    "engineeringSubcategory": "QA & Automation",
    "technologies": [
      "Java",
      "TypeScript",
      "SQL",
      "Docker",
      "AWS"
    ],
    "jobType": "Full-time",
    "workplaceType": "Hybrid",
    "experienceLevel": "Junior (1-3 yrs)",
    "isFresher": false,
    "fresherConfidence": 15,
    "isInternship": false,
    "salaryRange": "₹10,00,000 - ₹16,00,000 / yr",
    "location": "Olympia Tech Park, Guindy, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://www.go-yubi.com/careers/qa-engineer-chennai",
    "firstSeenAt": "2026-08-29T14:00:00Z",
    "lastSeenAt": "2026-09-01T11:30:00Z",
    "lastVerifiedAt": "2026-09-01T11:30:00Z",
    "freshnessStatus": "ACTIVE",
    "verificationStatus": "VERIFIED",
    "isFeatured": false,
    "isSeedData": true
  },
  {
    "id": "job-11",
    "companyId": "comp-6",
    "companyName": "The ePlane Company",
    "companyLogo": "https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Tidel Park & Tharamani",
    "title": "Autonomous Navigation & Robotics Graduate Intern",
    "slug": "eplane-robotics-navigation-intern",
    "descriptionSnippet": "Join our eVTOL flight testing team at IIT Madras Research Park. Work on sensor fusion (LiDAR, Radar, IMU), obstacle avoidance, and path planning for autonomous electric flying aircraft.",
    "primaryCategory": "DeepTech & AI",
    "isEngineering": true,
    "engineeringSubcategory": "ML & AI Engineering",
    "technologies": [
      "C++",
      "Python",
      "ROS",
      "Machine Learning",
      "Linux"
    ],
    "jobType": "Internship",
    "workplaceType": "On-site",
    "experienceLevel": "Fresher / Entry (0-1 yrs)",
    "isFresher": true,
    "fresherConfidence": 96,
    "isInternship": true,
    "salaryRange": "₹30,000 - ₹45,000 / month stipend",
    "location": "IIT Madras Research Park, Tharamani, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 100,
    "sourceName": "Company Careers",
    "originalUrl": "https://eplane.ai/careers/autonomy-intern",
    "firstSeenAt": "2026-09-01T07:00:00Z",
    "lastSeenAt": "2026-09-01T15:00:00Z",
    "lastVerifiedAt": "2026-09-01T15:00:00Z",
    "freshnessStatus": "NEW",
    "verificationStatus": "VERIFIED",
    "isFeatured": true,
    "isSeedData": true
  },
  {
    "id": "job-12",
    "companyId": "comp-12",
    "companyName": "Garuda Aerospace",
    "companyLogo": "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=128&auto=format&fit=crop&q=80",
    "companyHub": "Anna Nagar / Central Chennai",
    "title": "Junior Drone Systems & Python Telemetry Engineer",
    "slug": "garuda-drone-python-telemetry-engineer",
    "descriptionSnippet": "Develop real-time telemetry streaming and ground control station software for agri and defense drones. Open to recent graduates with solid Python, Linux, and networking skills.",
    "primaryCategory": "Hardware & IoT",
    "isEngineering": true,
    "engineeringSubcategory": "Embedded & IoT",
    "technologies": [
      "Python",
      "C++",
      "Embedded & IoT",
      "Linux"
    ],
    "jobType": "Full-time",
    "workplaceType": "On-site",
    "experienceLevel": "Fresher / Entry (0-1 yrs)",
    "isFresher": true,
    "fresherConfidence": 85,
    "isInternship": false,
    "salaryRange": "₹5,50,000 - ₹8,00,000 / yr",
    "location": "Anna Nagar East, Chennai",
    "chennaiRelevance": "CHENNAI_CONFIRMED",
    "relevanceConfidence": 95,
    "sourceName": "LinkedIn",
    "originalUrl": "https://linkedin.com/jobs/view/garuda-drone-telemetry-chennai",
    "firstSeenAt": "2026-09-01T05:30:00Z",
    "lastSeenAt": "2026-09-01T14:00:00Z",
    "lastVerifiedAt": "2026-09-01T14:00:00Z",
    "freshnessStatus": "NEW",
    "verificationStatus": "VERIFIED",
    "isFeatured": false,
    "isSeedData": true
  }
];
