// <auto-generated />
using System;
using System.Collections.Generic;
using ChennaiStartupJobsMap.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChennaiStartupJobsMap.Api.Migrations
{
    [DbContext(typeof(ChennaiDbContext))]
    [Migration("20260912060222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "usr-admin-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@chennaistartups.in",
                            IsVerified = true,
                            Name = "Chennai Admin",
                            PasswordHash = "vN/1fEw76LdJ14wXlD3F14l5f9U1lH/eQ+F5uK4jE1w=",
                            Role = "ADMIN",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "usr-mod-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "moderator@chennaistartups.in",
                            IsVerified = true,
                            Name = "Ecosystem Moderator",
                            PasswordHash = "vN/1fEw76LdJ14wXlD3F14l5f9U1lH/eQ+F5uK4jE1w=",
                            Role = "MODERATOR",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "usr-recruiter-1",
                            CompanyId = "comp-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "recruiter@zoho.com",
                            IsVerified = true,
                            Name = "Zoho Talent Team",
                            PasswordHash = "vN/1fEw76LdJ14wXlD3F14l5f9U1lH/eQ+F5uK4jE1w=",
                            Role = "RECRUITER",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "usr-demo-1",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@chennaistartups.in",
                            IsVerified = true,
                            Name = "Karthik Developer",
                            PasswordHash = "vN/1fEw76LdJ14wXlD3F14l5f9U1lH/eQ+F5uK4jE1w=",
                            Role = "USER",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.AnalyticsEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("UserIdentifierHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.CareerSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CareersUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobsApiUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CareerSources");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareersUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChennaiLocations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChennaiPresence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChennaiRelevanceScore")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeCount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("FundingStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headquarters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HiringStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MapPrecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialCareersUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficialWebsite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubCategory")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("TechnologyTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TotalFundingRaised")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("HiringStatus");

                    b.HasIndex("Hub");

                    b.HasIndex("Industry");

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("VerificationStatus");

                    b.HasIndex("Website");

                    b.HasIndex("Hub", "VerificationStatus");

                    b.HasIndex("IsActive", "FoundedYear");

                    b.HasIndex("IsActive", "HiringStatus");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = "comp-1",
                            Address = "Estancia IT Park, Plot No. 140 & 151, GST Road / OMR Corridor, Chennai",
                            CareersUrl = "https://www.zoho.com/careers/",
                            Categories = "SaaS / Enterprise Software,DeepTech & AI",
                            Category = "SaaS / Enterprise Software",
                            ChennaiLocations = "",
                            ChennaiPresence = "Headquarters / Technology Center",
                            ChennaiRelevanceScore = 100,
                            City = "Chennai",
                            CompanyType = "PRODUCT COMPANY",
                            CompanyTypes = "PRODUCT COMPANY,ENTERPRISE,STARTUP",
                            ConfidenceScore = 95,
                            Country = "India",
                            CreatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 59, DateTimeKind.Utc).AddTicks(2307),
                            Description = "Zoho offers a comprehensive suite of cloud software applications for businesses worldwide. Bootstrapped from Chennai with tens of millions of users across 150+ countries.",
                            DiscoveredAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeCount = "15,000+",
                            EmployeeRange = "15,000+",
                            FoundedYear = 1996,
                            FundingStage = "Bootstrapped",
                            Headquarters = "Chennai, Tamil Nadu",
                            HiringStatus = "Hiring Surge",
                            Hub = "OMR (IT Corridor)",
                            Industry = "Technology",
                            IsActive = true,
                            IsFeatured = true,
                            IsSeedData = true,
                            LastVerifiedAt = new DateTime(2026, 9, 12, 6, 2, 19, 63, DateTimeKind.Utc).AddTicks(8863),
                            Latitude = 12.825200000000001,
                            Logo = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
                            LogoUrl = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
                            Longitude = 80.043499999999995,
                            MapPrecision = "exact",
                            Name = "Zoho Corporation",
                            NormalizedName = "zoho corporation",
                            OfficialCareersUrl = "https://www.zoho.com/careers/",
                            OfficialWebsite = "https://www.zoho.com",
                            ShortDescription = "Bootstrapped Global SaaS Titan & Tech Powerhouse",
                            Skills = new List<string> { "Java", "C++", "React", "Python", "PostgreSQL" },
                            Slug = "zoho",
                            SourceName = "Company Careers",
                            SourceType = "OFFICIAL_WEBSITE",
                            SourceUrl = "https://www.zoho.com/careers/",
                            State = "Tamil Nadu",
                            Tagline = "Bootstrapped Global SaaS Titan & Tech Powerhouse",
                            Tags = "SaaS,Cloud CRM,Bootstrapped",
                            TechStack = "Java,C++,React,Python,PostgreSQL",
                            TechnologyTags = new List<string> { "SaaS", "Cloud CRM", "Bootstrapped" },
                            TotalFundingRaised = "Self-Funded ($1B+ Annual Revenue)",
                            UpdatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 59, DateTimeKind.Utc).AddTicks(2308),
                            VerificationMethod = "OFFICIAL_DOMAIN_AUDIT",
                            VerificationStatus = "VERIFIED",
                            Website = "https://www.zoho.com"
                        },
                        new
                        {
                            Id = "comp-2",
                            Address = "Block B, Global Infocity Park, 40 MGR Salai, Perungudi, Chennai 600096",
                            CareersUrl = "https://www.freshworks.com/company/careers/",
                            Categories = "SaaS / Enterprise Software,DeepTech & AI",
                            Category = "SaaS / Enterprise Software",
                            ChennaiLocations = "",
                            ChennaiPresence = "Headquarters / Technology Center",
                            ChennaiRelevanceScore = 100,
                            City = "Chennai",
                            CompanyType = "PRODUCT COMPANY",
                            CompanyTypes = "PRODUCT COMPANY,MNC,ENTERPRISE",
                            ConfidenceScore = 95,
                            Country = "India",
                            CreatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 64, DateTimeKind.Utc).AddTicks(327),
                            Description = "Born in Chennai, Freshworks makes innovative customer engagement and ITSM software for over 60,000 businesses globally.",
                            DiscoveredAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeCount = "5,000+",
                            EmployeeRange = "5,000+",
                            FoundedYear = 2010,
                            FundingStage = "Public / IPO",
                            Headquarters = "Chennai, Tamil Nadu",
                            HiringStatus = "Active",
                            Hub = "Perungudi & Kandanchavadi",
                            Industry = "Technology",
                            IsActive = true,
                            IsFeatured = true,
                            IsSeedData = true,
                            LastVerifiedAt = new DateTime(2026, 9, 12, 6, 2, 19, 64, DateTimeKind.Utc).AddTicks(439),
                            Latitude = 12.964399999999999,
                            Logo = "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=128&auto=format&fit=crop&q=80",
                            LogoUrl = "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=128&auto=format&fit=crop&q=80",
                            Longitude = 80.242699999999999,
                            MapPrecision = "exact",
                            Name = "Freshworks",
                            NormalizedName = "freshworks",
                            OfficialCareersUrl = "https://www.freshworks.com/company/careers/",
                            OfficialWebsite = "https://www.freshworks.com",
                            ShortDescription = "Modern AI-powered Customer Experience & IT Service Software",
                            Skills = new List<string> { "Ruby on Rails", "Java", "React", "AWS", "Python" },
                            Slug = "freshworks",
                            SourceName = "Company Careers",
                            SourceType = "OFFICIAL_WEBSITE",
                            SourceUrl = "https://www.freshworks.com/company/careers/",
                            State = "Tamil Nadu",
                            Tagline = "Modern AI-powered Customer Experience & IT Service Software",
                            Tags = "SaaS,Nasdaq Listed,CRM",
                            TechStack = "Ruby on Rails,Java,React,AWS,Python",
                            TechnologyTags = new List<string> { "SaaS", "Nasdaq Listed", "CRM" },
                            TotalFundingRaised = "Nasdaq: FRSH ($1.03B IPO)",
                            UpdatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 64, DateTimeKind.Utc).AddTicks(327),
                            VerificationMethod = "OFFICIAL_DOMAIN_AUDIT",
                            VerificationStatus = "VERIFIED",
                            Website = "https://www.freshworks.com"
                        });
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.CompanyClaim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorporateEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProofNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("CompanyClaims");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.CompanySource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanySources");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.IngestionRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuplicatesFound")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<int>("ErrorsCount")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsDiscovered")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsSkipped")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IngestionRuns");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApplyUrl")
                        .HasColumnType("text");

                    b.Property<string>("ChennaiRelevance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyHub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyLogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescriptionSnippet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DuplicateGroupId")
                        .HasColumnType("text");

                    b.Property<string>("EngineeringSubcategory")
                        .HasColumnType("text");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ExperienceMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExperienceMin")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FresherConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("FreshnessStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEngineering")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFresher")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInternship")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelevanceConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("SalaryCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SalaryMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("SalaryMin")
                        .HasColumnType("double precision");

                    b.Property<string>("SalaryRange")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRecordId")
                        .HasColumnType("text");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkplaceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyHub");

                    b.HasIndex("CompanyId");

                    b.HasIndex("FreshnessStatus");

                    b.HasIndex("IsEngineering");

                    b.HasIndex("IsFresher");

                    b.HasIndex("NormalizedTitle");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("CompanyId", "IsActive");

                    b.HasIndex("IsActive", "IsFresher");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = "job-1",
                            ApplyUrl = "https://www.zoho.com/careers/job-details.html?id=fresher-dev-chennai",
                            ChennaiRelevance = "CHENNAI_CONFIRMED",
                            CompanyHub = "OMR (IT Corridor)",
                            CompanyId = "comp-1",
                            CompanyLogo = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80",
                            CompanyName = "Zoho Corporation",
                            CreatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 66, DateTimeKind.Utc).AddTicks(1829),
                            DescriptionSnippet = "We are hiring fresh engineering graduates to work on Zoho core product suites, database engines, and AI applications. Open to 0-1 years of experience in Java, C++, or Python.",
                            EngineeringSubcategory = "Software Engineering",
                            ExperienceLevel = "Fresher / Entry (0-1 yrs)",
                            ExperienceMax = 1.0,
                            ExperienceMin = 0.0,
                            FirstSeenAt = new DateTime(2026, 9, 10, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(2196),
                            FresherConfidence = 98,
                            FreshnessStatus = "NEW",
                            IsActive = true,
                            IsEngineering = true,
                            IsFeatured = true,
                            IsFresher = true,
                            IsInternship = false,
                            IsSeedData = true,
                            JobType = "Full-time",
                            LastSeenAt = new DateTime(2026, 9, 12, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(3052),
                            LastVerifiedAt = new DateTime(2026, 9, 12, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(3685),
                            Location = "Estancia IT Park / OMR, Chennai",
                            NormalizedTitle = "associate software developer freshers 2025 2026",
                            OriginalUrl = "https://www.zoho.com/careers/job-details.html?id=fresher-dev-chennai",
                            PrimaryCategory = "SaaS / Enterprise Software",
                            RelevanceConfidence = 100,
                            SalaryCurrency = "INR",
                            SalaryMax = 950000.0,
                            SalaryMin = 650000.0,
                            SalaryRange = "₹6,50,000 - ₹9,50,000 / yr",
                            Slug = "zoho-associate-software-developer-fresher",
                            SourceName = "Company Careers",
                            Technologies = "Java,C++,Python,SQL",
                            Title = "Associate Software Developer (Freshers 2025/2026)",
                            UpdatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 66, DateTimeKind.Utc).AddTicks(1829),
                            VerificationStatus = "VERIFIED",
                            WorkplaceType = "On-site"
                        },
                        new
                        {
                            Id = "job-2",
                            ApplyUrl = "https://www.freshworks.com/company/careers/job-frontend-intern",
                            ChennaiRelevance = "CHENNAI_CONFIRMED",
                            CompanyHub = "Perungudi & Kandanchavadi",
                            CompanyId = "comp-2",
                            CompanyLogo = "https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=128&auto=format&fit=crop&q=80",
                            CompanyName = "Freshworks",
                            CreatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(7391),
                            DescriptionSnippet = "Looking for a passionate React frontend intern to build slick customer experience UI components for Freshdesk.",
                            EngineeringSubcategory = "Frontend",
                            ExperienceLevel = "Fresher / Entry (0-1 yrs)",
                            ExperienceMax = 0.5,
                            ExperienceMin = 0.0,
                            FirstSeenAt = new DateTime(2026, 9, 11, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(7430),
                            FresherConfidence = 95,
                            FreshnessStatus = "NEW",
                            IsActive = true,
                            IsEngineering = true,
                            IsFeatured = true,
                            IsFresher = true,
                            IsInternship = true,
                            IsSeedData = true,
                            JobType = "Internship",
                            LastSeenAt = new DateTime(2026, 9, 12, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(7450),
                            LastVerifiedAt = new DateTime(2026, 9, 12, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(7450),
                            Location = "Global Infocity, Perungudi, OMR, Chennai",
                            NormalizedTitle = "frontend engineer intern react typescript",
                            OriginalUrl = "https://www.freshworks.com/company/careers/job-frontend-intern",
                            PrimaryCategory = "SaaS / Enterprise Software",
                            RelevanceConfidence = 100,
                            SalaryCurrency = "INR",
                            SalaryRange = "₹35,000 / month Stipend",
                            Slug = "freshworks-frontend-engineer-intern",
                            SourceName = "Company Careers",
                            Technologies = "React,TypeScript,JavaScript",
                            Title = "Frontend Engineer Intern (React / TypeScript)",
                            UpdatedAt = new DateTime(2026, 9, 12, 6, 2, 19, 69, DateTimeKind.Utc).AddTicks(7391),
                            VerificationStatus = "VERIFIED",
                            WorkplaceType = "Hybrid"
                        });
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.JobAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FiltersJson")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobAlerts");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Location", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Precision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.RawIngestionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawCompany")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RawIngestionRecords");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.SavedCompany", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("SavedCompanies");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.SavedJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique();

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Technology", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Synonyms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.UserSubmission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Hub")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleOrName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.CareerSource", b =>
                {
                    b.HasOne("ChennaiStartupJobsMap.Api.Models.Company", "Company")
                        .WithMany("CareerSources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.CompanyClaim", b =>
                {
                    b.HasOne("ChennaiStartupJobsMap.Api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.CompanySource", b =>
                {
                    b.HasOne("ChennaiStartupJobsMap.Api.Models.Company", "Company")
                        .WithMany("Sources")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Job", b =>
                {
                    b.HasOne("ChennaiStartupJobsMap.Api.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.SavedCompany", b =>
                {
                    b.HasOne("ChennaiStartupJobsMap.Api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.SavedJob", b =>
                {
                    b.HasOne("ChennaiStartupJobsMap.Api.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ChennaiStartupJobsMap.Api.Models.Company", b =>
                {
                    b.Navigation("CareerSources");

                    b.Navigation("Jobs");

                    b.Navigation("Sources");
                });
#pragma warning restore 612, 618
        }
    }
}
