const fs = require('fs');

const companies = [
  {
    id: 'comp-1',
    name: 'Zoho Corporation',
    slug: 'zoho',
    tagline: 'Bootstrapped Global SaaS Titan & Tech Powerhouse',
    description: 'Zoho offers a comprehensive suite of cloud software applications for businesses worldwide. Bootstrapped from Chennai with tens of millions of users across 150+ countries.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    website: 'https://www.zoho.com',
    careersUrl: 'https://www.zoho.com/careers/',
    companyTypes: ['PRODUCT COMPANY', 'ENTERPRISE', 'STARTUP'],
    categories: ['SaaS / Enterprise Software', 'DeepTech & AI'],
    hub: 'OMR (IT Corridor)',
    address: 'Estancia IT Park, Plot No. 140 & 151, GST Road / OMR Corridor, Chennai',
    coordinates: { lat: 12.8252, lng: 80.0435 },
    foundedYear: 1996,
    employeeCount: '15,000+',
    fundingStage: 'Bootstrapped',
    totalFundingRaised: 'Self-Funded ($1B+ Annual Revenue)',
    hiringStatus: 'Hiring Surge',
    tags: ['SaaS', 'Cloud CRM', 'Enterprise Suites', 'Bootstrapped', 'AI'],
    techStack: ['Java', 'C++', 'React', 'Python', 'Deluge', 'PostgreSQL', 'AI/LLM', 'Linux'],
    verificationStatus: 'VERIFIED',
    isFeatured: true,
    isSeedData: true,
    sourceName: 'Company Careers',
    sourceUrl: 'https://www.zoho.com/careers/',
    discoveredAt: '2026-08-01T00:00:00Z',
    lastVerifiedAt: '2026-09-01T08:00:00Z',
    socialLinks: { linkedin: 'https://www.linkedin.com/company/zoho', twitter: 'https://twitter.com/zoho', github: 'https://github.com/zoho' },
    keyLeaders: { founders: ['Sridhar Vembu', 'Tony Thomas'], leadership: ['Mani Vembu', 'Prashanth H'] }
  },
  {
    id: 'comp-2',
    name: 'Freshworks',
    slug: 'freshworks',
    tagline: 'Modern AI-powered Customer Experience & IT Service Software',
    description: 'Born in Chennai, Freshworks makes innovative customer engagement and ITSM software for over 60,000 businesses globally. First Indian SaaS company listed on Nasdaq.',
    logo: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=128&auto=format&fit=crop&q=80',
    website: 'https://www.freshworks.com',
    careersUrl: 'https://www.freshworks.com/company/careers/',
    companyTypes: ['PRODUCT COMPANY', 'MNC', 'ENTERPRISE'],
    categories: ['SaaS / Enterprise Software', 'DeepTech & AI'],
    hub: 'Perungudi & Kandanchavadi',
    address: 'Block B, Global Infocity Park, 40 MGR Salai, Perungudi, Chennai, Tamil Nadu 600096',
    coordinates: { lat: 12.9644, lng: 80.2427 },
    foundedYear: 2010,
    employeeCount: '5,000+',
    fundingStage: 'Public / IPO',
    totalFundingRaised: 'Nasdaq: FRSH ($1.03B IPO)',
    hiringStatus: 'Active',
    tags: ['SaaS', 'ITSM', 'Customer Support', 'Freddy AI', 'Public'],
    techStack: ['Ruby on Rails', 'React', 'TypeScript', 'Node.js', 'AWS', 'Python', 'Kafka'],
    verificationStatus: 'VERIFIED',
    isFeatured: true,
    isSeedData: true,
    sourceName: 'Company Careers',
    sourceUrl: 'https://www.freshworks.com/company/careers/',
    discoveredAt: '2026-08-01T00:00:00Z',
    lastVerifiedAt: '2026-09-01T08:30:00Z',
    socialLinks: { linkedin: 'https://www.linkedin.com/company/freshworks-inc', twitter: 'https://twitter.com/FreshworksInc', github: 'https://github.com/freshworks' },
    keyLeaders: { founders: ['Girish Mathrubootham', 'Shan Krishnasamy'], leadership: ['Dennis Woodside'] }
  },
  {
    id: 'comp-3',
    name: 'Chargebee',
    slug: 'chargebee',
    tagline: 'Subscription Management & Recurring Billing Infrastructure',
    description: 'Chargebee is a leading revenue management and subscription billing platform powering high-growth SaaS and subscription businesses across the globe.',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80',
    website: 'https://www.chargebee.com',
    careersUrl: 'https://www.chargebee.com/careers/',
    companyTypes: ['PRODUCT COMPANY', 'STARTUP'],
    categories: ['SaaS / Enterprise Software', 'FinTech'],
    hub: 'Sholinganallur',
    address: 'Tower 3, World Trade Center / Brigade Vantage, OMR, Sholinganallur, Chennai, Tamil Nadu 600119',
    coordinates: { lat: 12.9010, lng: 80.2279 },
    foundedYear: 2011,
    employeeCount: '1,200+',
    fundingStage: 'Series C+',
    totalFundingRaised: '$470M (Tiger Global, Sequoia, Insight Partners)',
    hiringStatus: 'Active',
    tags: ['SaaS', 'Billing', 'Fintech', 'Unicorn', 'Subscriptions'],
    techStack: ['Java', 'Spring Boot', 'React', 'TypeScript', 'AWS', 'PostgreSQL', 'Redis', 'Kafka'],
    verificationStatus: 'VERIFIED',
    isFeatured: true,
    isSeedData: true,
    sourceName: 'Company Careers',
    sourceUrl: 'https://www.chargebee.com/careers/',
    discoveredAt: '2026-08-01T00:00:00Z',
    lastVerifiedAt: '2026-09-01T09:00:00Z',
    socialLinks: { linkedin: 'https://www.linkedin.com/company/chargebee', twitter: 'https://twitter.com/chargebee' },
    keyLeaders: { founders: ['Krish Subramanian', 'Rajaraman Santhanam', 'Thiyagarajan T', 'Saravanan KP'] }
  },
  {
    id: 'comp-4',
    name: 'Kissflow',
    slug: 'kissflow',
    tagline: 'Digital Workplace & Low-Code Workflow Automation Platform',
    description: 'Kissflow provides a unified low-code and digital workplace platform for managing business processes, projects, case management, and team collaboration.',
    logo: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    website: 'https://kissflow.com',
    careersUrl: 'https://kissflow.com/careers/',
    companyTypes: ['PRODUCT COMPANY', 'STARTUP'],
    categories: ['SaaS / Enterprise Software', 'DeepTech & AI'],
    hub: 'Perungudi & Kandanchavadi',
    address: 'World Trade Center, 142/424, Rajiv Gandhi Salai (OMR), Perungudi, Chennai 600096',
    coordinates: { lat: 12.9698, lng: 80.2462 },
    foundedYear: 2003,
    employeeCount: '450+',
    fundingStage: 'Profitable & Self-Sustained',
    totalFundingRaised: 'Self-Funded / Bootstrapped',
    hiringStatus: 'Active',
    tags: ['Low-Code', 'SaaS', 'Workflow', 'B2B', 'Culture-First'],
    techStack: ['Python', 'Node.js', 'React', 'Angular', 'GCP', 'Kubernetes', 'MongoDB'],
    verificationStatus: 'VERIFIED',
    isFeatured: true,
    isSeedData: true,
    sourceName: 'Company Careers',
    sourceUrl: 'https://kissflow.com/careers/',
    discoveredAt: '2026-08-01T00:00:00Z',
    lastVerifiedAt: '2026-09-01T09:15:00Z',
    socialLinks: { linkedin: 'https://www.linkedin.com/company/kissflow', twitter: 'https://twitter.com/kissflow' },
    keyLeaders: { founders: ['Suresh Sambandam'] }
  }
];

fs.writeFileSync('scratch/companies_part1.json', JSON.stringify(companies), 'utf8');
